### ISSUE TITLE
Microsoft.AspNet.Diagnostics.Tests failures on CoreCLR on Linux

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Diagnostics#191]
info: Exec
    info:   program: /usr/bin/env
    info:   commandline: bash -c ". \"/home/cesars/src/aspnet/universe/Diagnostics/packages/KoreBuild/build/dnvm.sh\"; dnvm run default -runtime coreclr test"
    info:   workingdir: test/Microsoft.AspNet.Diagnostics.Tests
    xUnit.net DNX Runner (64-bit DNXCore 5.0)
      Discovering: Microsoft.AspNet.Diagnostics.Tests
      Discovered:  Microsoft.AspNet.Diagnostics.Tests
      Starting:    Microsoft.AspNet.Diagnostics.Tests
          Assert.Equal() Failure
          Expected: 4
          Actual:   0
          Stack Trace:
               at Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddlewareTest.UsesDefaultFileProvider_IfNotProvidedOnOptions(String relativePath)
               at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
               at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
               at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
          Assert.Equal() Failure
          Expected: 4
          Actual:   0
          Stack Trace:
               at Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddlewareTest.DisplaysSourceCodeLines_ForRelativePaths(String relativePath)
               at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
               at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
               at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      Finished:    Microsoft.AspNet.Diagnostics.Tests
    === TEST EXECUTION SUMMARY ===
       Microsoft.AspNet.Diagnostics.Tests  Total: 49, Errors: 0, Failed: 2, Skipped: 0, Time: 3.501s

**Comment by cesarbs** [comment]
This affects https://github.com/aspnet/Universe/issues/304.
