### ISSUE TITLE
UseStatusCodePagesWithReExecute should support ~/

### ISSUE THREAD

**Issue by rynowak** [aspnet/Diagnostics#283]
```
System.ArgumentException: The path in 'value' must start with '/'.
Parameter name: value
   at Microsoft.AspNetCore.Http.PathString..ctor(String value)
   at Microsoft.AspNetCore.Builder.StatusCodePagesExtensions.<>c__DisplayClass6_0.<<UseStatusCodePagesWithReExecute>b__0
>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**Comment by Tratcher** [comment]
I suspect `/` already does what you'd want `~/` to do, no?

**Comment by rynowak** [comment]
Yes `/Foo` is equivalent to what `~/Foo` would do.

What's missing/inconsistent (comparing to the redirect feature) is that in that case `/Foo` ignores `PathBase`. 

https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesExtensions.cs#L114

**Comment by Tratcher** [comment]
I don't think it would make sense to re-execute a request with a different PathBase. If you wanted to do that you should put the middleware at a higher scope or use the redirect option.

**Comment by Eilon** [comment]
Not planning on supporting this here. They ultimately mean the same thing because this API only deals "within the app" so that's as much "root" as it has access to anyway. This isn't an unreasonable request, but I'm not sure if people will be confused at this.
