### ISSUE TITLE
UseExceptionHandler with redirect path should support ~/

### ISSUE THREAD

**Issue by rynowak** [aspnet/Diagnostics#284]
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocati
on. ---> System.ArgumentException: The path in 'value' must start with '/'.
Parameter name: value
   at Microsoft.AspNetCore.Http.PathString..ctor(String value)
   at Microsoft.AspNetCore.Builder.ExceptionHandlerExtensions.UseExceptionHandler(IApplicationBuilder app, String errorH
andlingPath)
   at WebApp.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApp.Program.Main(String[] args)
```

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/Diagnostics/issues/283

**Comment by Eilon** [comment]
Not planning on supporting this here. They ultimately mean the same thing because this API only deals "within the app" so that's as much "root" as it has access to anyway. This isn't an unreasonable request, but I'm not sure if people will be confused at this.
