### ISSUE TITLE
Flaky Test: EntityFrameworkCore.Tests.DatabaseErrorPageMiddlewareTest.Pass_thru_when_context_not_in_services

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Diagnostics#366]
```
[Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.Tests.DatabaseErrorPageMiddlewareTest.Pass_thru_when_context_not_in_services] Assert.Throws() Failure
Expected: typeof(System.Data.SqlClient.SqlException)
Actual:   typeof(System.InvalidOperationException): An exception has been raised that is likely due to a transient failure. If you are connecting to a SQL Azure database consider using SqlAzureExecutionStrategy.
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.Tests.DatabaseErrorPageMiddlewareTest.ContextNotRegisteredInServicesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.Tests.DatabaseErrorPageMiddlewareTest.<>c__DisplayClass15_0.<<Pass_thru_when_context_not_in_services>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

# Timeline
* 4/25/17: http://aspnetci/viewLog.html?buildId=208072&buildTypeId=Lite_MvcTest&tab=buildLog&filter=err
* 4/25/17: All builds of Win10Universe starting with 24617 (4/24/17 7:08 PM)
* 4/25/17: Attempted fix https://github.com/aspnet/Diagnostics/commit/c73bd7e63e9b505a04dca9937c2cfdf0548b7dc8
* 4/25/17: http://aspnetci/viewLog.html?buildId=208746&buildTypeId=Lite_MvcTest&tab=buildLog&filter=err
* 4/26/17: http://aspnetci/viewLog.html?buildId=209060&buildTypeId=Lite_MvcTest&tab=buildLog&filter=err

**Comment by mikeharder** [comment]
@smitpatel: Can you take a quick look at this test?  It's flaky on certain build configs, but it's also started failing every build on Win10 which needs to be addressed ASAP.

**Comment by smitpatel** [comment]
@AndriySvyryd - Any insights?

**Comment by mikeharder** [comment]
Also failing on all builds of Win8-Universe starting with 1860 (4/25/17 12:52 AM).

**Comment by mikeharder** [comment]
@bricelam: Do you know anything about this?  @Eilon thought you might.

**Comment by bricelam** [comment]
Not sure. Are there any `Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.FunctionalTests.Scratch_#` databases leftover on the agent from previous runs?

**Comment by AndriySvyryd** [comment]
The test says that the DbContext shouldn't be involved so it might be an issue in the services being registered

**Comment by mikeharder** [comment]
Checking...

**Comment by AndriySvyryd** [comment]
We can increase the timeout to what we use in the EF repo https://github.com/aspnet/Diagnostics/pull/367

**Comment by AndriySvyryd** [comment]
Optimistically assuming this is fixed by c73bd7e

**Comment by mikeharder** [comment]
Hit this again with the increased timeouts.  See list of repros in top comment.

**Comment by pranavkm** [comment]
Yup, one more of these that failed now.

**Comment by AndriySvyryd** [comment]
I'll just modify the test to treat this as success, since the specific error is not important here https://github.com/aspnet/Diagnostics/pull/369
